// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package generator

import (
	"github.com/hirasawayuki/go-oauth-server/controller"
	"github.com/hirasawayuki/go-oauth-server/handler"
	"github.com/hirasawayuki/go-oauth-server/registry"
	"github.com/hirasawayuki/go-oauth-server/repository"
	"github.com/hirasawayuki/go-oauth-server/usecase"
)

// Injectors from wire.go:

func InitializeAppHandler() (handler.AppHandler, func(), error) {
	store, cleanup, err := registry.NewStore()
	if err != nil {
		return handler.AppHandler{}, nil, err
	}
	clientRepository := &repository.ClientRepository{
		Store: store,
	}
	clientGetUseCase := &usecase.ClientGetUseCase{
		ClientRepository: clientRepository,
	}
	clientController := &controller.ClientController{
		ClientGetUseCase: clientGetUseCase,
	}
	authorizeHandler := &handler.AuthorizeHandler{
		ClientController: clientController,
	}
	appHandler := handler.AppHandler{
		AuthorizeHandler: authorizeHandler,
	}
	return appHandler, func() {
		cleanup()
	}, nil
}
